experiment_name: hello-world-error-h100
environment:
  env_variables:
    NCCL_DEBUG: "INFO"
  dependencies: dependencies.yaml
compute:
  gpus: 8
  gpu_type: H100
max_retries: 0
code_source:
  type: snapshot
  snapshot:
    # allow_uncommitted: true
    repo_path: /Users/guanyu.chen/Documents/Projects/composer_geneformer_pretrain/
    include_paths:
      - SGC_hello_world_error
command: |-
  echo ">>> Hello world error test (H100)"
  cd $CODE_SOURCE_PATH/composer_geneformer_pretrain/SGC_hello_world_error
  torchrun \
    --nnodes=1 \
    --nproc_per_node=8 \
    --node_rank=$NODE_RANK \
    --master_addr=$MASTER_ADDR \
    --master_port=$MASTER_PORT \
    train.py
